### ISSUE TITLE
Suggestion is only displayed for few seconds

### ISSUE THREAD

**Issue by antho1404** [oclif/plugin-not-found#29]
https://github.com/oclif/plugin-not-found/blob/0634f4c225ec5d6e9452dd8040f9c46bc3f561ca/src/index.ts#L30

Why is the suggestion only displayed for a few seconds? It could be great to have no timeout (and the user exit the command or just press no) or even better have the possibility to customize it with no timeout or the timeout of our choice

**Comment by mattbishop** [comment]
Or, make it configurable so we can decide what the timeout should be.
